---
title: "Lab9a"
author: "Chris Colvin"
date: "10/28/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```

if(<condition>) {
        ## do something
} 
## Continue with rest of code

if(<condition>) {
        ## do something
} 
else {
        ## do something else
}
if(<condition1>) {
        ## do something
} else if(<condition2>)  {
        ## do something different
} else {
        ## do something different
}
## Generate a uniform random number
x <- runif(1, 0, 10)  
if(x > 3) {
        y <- 10
} else {
        y <- 0
}
```{r}
for(i in 1:10) {
        print(i)
}
```

```{r}
x <- c("a", "b", "c", "d")
for(i in 1:4) {
        ## Print out each element of 'x'
        print(x[i])  
}
```
```{r}
## Generate a sequence based on length of 'x'
for(i in seq_along(x)) {   
        print(x[i])
}
```

```{r}
for(letter in x) {
        print(letter)
}
```

```{r}
for(i in 1:4) print(x[i])
```

# Nested for loops
```{r}
x <- matrix(1:6, 2, 3)
for(i in seq_len(nrow(x))) {
        for(j in seq_len(ncol(x))) {
                print(x[i, j])
        }   
}
```

# while Loops
```{r}
count <- 0
while(count < 10) {
        print(count)
        count <- count + 1
}
```

```{r}
z <- 5
set.seed(1)
while(z >= 3 && z <= 10) {
        coin <- rbinom(1, 1, 0.5)
        
        if(coin == 1) {  ## random walk
                z <- z + 1
        } else {
                z <- z - 1
        } 
}
print(z)
```

```{r}
> f <- function() {
+         ## This is an empty function
+ }
> ## Functions have their own class
> class(f)  
[1] "function"
> ## Execute this function
> f()       
NULL
```

```{r}
> f <- function() {
+         cat("Hello, world!\n")
+ }
> f()
Hello, world!
```

```{r}
> f <- function(num) {
+         for(i in seq_len(num)) {
+                 cat("Hello, world!\n")
+         }
+ }
> f(3)
Hello, world!
Hello, world!
Hello, world!
```

```{r}
> f <- function(num) {
+         hello <- "Hello, world!\n"
+         for(i in seq_len(num)) {
+                 cat(hello)
+         }
+         chars <- nchar(hello) * num
+         chars
+ }
> meaningoflife <- f(3)
Hello, world!
Hello, world!
Hello, world!
> print(meaningoflife)
[1] 42
```

```{r}
> f()
Error in f(): argument "num" is missing, with no default
```

```{r}
> f <- function(num = 1) {
+         hello <- "Hello, world!\n"
+         for(i in seq_len(num)) {
+                 cat(hello)
+         }
+         chars <- nchar(hello) * num
+         chars
+ }
> f()    ## Use default value for 'num'
Hello, world!
[1] 14
> f(2)   ## Use user-specified value
Hello, world!
Hello, world!
[1] 28
```

```{r}
> f(num = 6)
Hello, world!
Hello, world!
[1] 28
```

